recommender:
  resources:
    requests:
      cpu: 50m
      memory: 200Mi
    limits:
      cpu: 150m
      memory: 750Mi
  extraArgs:
    kube-api-qps: 20
    kube-api-burst: 50
    checkpoints-gc-interval: 6h0m0s
admissionController:
  useHostNetwork: true
  httpPort: 11000
  v: 6
