apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: nginx-test-deployment-set
  namespace: argocd
spec:
  generators:
    - clusters:
        selector:
          matchExpressions:
            - key: envLabel
              operator: In
              values:
                - dev
            - key: upgrade
              operator: In
              values:
                - auto                
        values:
          envLabel: '{{ index .metadata.labels "envLabel" }}'
          ci: '{{ index .metadata.labels "ci" }}'
          upgrade: '{{ index .metadata.labels "upgrade" }}'
  strategy:
    type: RollingSync
    rollingSync:
      steps:
        - matchExpressions:
            - key: envLabel
              operator: In
              values:
                - dev
            - key: upgrade
              operator: In
              values:
                - auto
          maxUpdate: 1
        - matchExpressions:
            - key: envLabel
              operator: In
              values:
                - prod
          maxUpdate: 1
  goTemplate: true
  goTemplateOptions: ["missingkey=error"] 
  template:
    metadata:
      name: 'nginx-test-deployment-{{ .values.ci }}'
      labels:
        envLabel: '{{ .values.envLabel }}'
        upgrade: '{{ .values.upgrade }}'
    spec:
      project: default
      source:
        repoURL: https://github.com/ncmuthu/argocd-app-vpa.git
        targetRevision: HEAD
        path: argocd
      destination:
        server: '{{.server}}'
        namespace: argocd
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
