apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: vpa
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  applyNestedSelectors: true
  generators:
    - matrix:
        generators:
        - clusters:
            selector:
              matchExpressions:
              - key: k8s.autodesk.com/cluster-class
                operator: In
                values:
                  - caas
              - key: k8s.autodesk.com/vpa
                operator: In
                values:
                  - enable
            values:
              moniker: '{{ index .metadata.labels "k8s.autodesk.com/moniker"}}'
              project: "default"
              env: '{{ index .metadata.labels "k8s.autodesk.com/env" }}'
              region: "us-west-2"
              eksversion: '{{ index .metadata.labels "k8s.autodesk.com/eksversion" }}'
              envLabel: '{{ index .metadata.labels "envLabel" }}'
              ci: '{{ index .metadata.labels "ci" }}'
              upgrade: '{{ index .metadata.labels "upgrade" }}'
              appname: 'vpa'
              cluster: '{{ .metadat.name }}'
        - merge:
            mergeKeys:
            - 'chart'
            generators:
            - git:
                repoURL: "https://github.com/ncmuthu/argocd-apps-of-app.git"
                revision: main
                files:
                - path: apps/common/{{ .values.appname }}/app.yaml
            - git:
                repoURL: "https://github.com/ncmuthu/argocd-apps-of-app.git"
                revision: main
                files:
                - path: apps/env/{{.values.env}}/{{ .values.appname }}/app.yaml
            - git:
                repoURL: "https://github.com/ncmuthu/argocd-apps-of-app.git"
                revision: main
                files:
                - path: apps/env/{{.values.env}}/{{ .values.appname }}/values-{{.values.region}}.yaml
            - git:
                repoURL: "https://github.com/ncmuthu/argocd-apps-of-app.git"
                revision: main
                files:
                - path: apps/env/{{.values.env}}/{{ .values.appname }}/values-eks-{{.values.eksversion}}.yaml
            - git:
                repoURL: "https://github.com/ncmuthu/argocd-apps-of-app.git"
                revision: main
                files:
                - path: apps/cluster/{{ .values.cluster}}/{{ .values.appname }}/app.yaml     
      selector:
        matchExpressions:
        - key: enabled
          operator: In
          values:
          - 'true'
  strategy:
    type: RollingSync
    rollingSync:
      steps:
        - matchExpressions:
            - key: k8s.autodesk.com/env
              operator: In
              values:
                - dev
                - prod
                - stage
          maxUpdate: 1
  template:
    metadata:
      name: '{{.values.moniker | lower}}-{{ .values.appname }}'
      labels:
        k8s.autodesk.com/env: '{{ .values.env }}'
        maxUpdate: '{{ .maxUpdate }}'
    spec:
      project: '{{ .values.project }}'
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
        syncOptions:
          - CreateNamespace=true
      sources:
      - repoURL: 'https://github.com/ncmuthu/argocd-apps-of-app.git'
        targetRevision: 'main'
        ref: helm
      - repoURL: '{{ .repoURL }}'
        chart: '{{.chart}}'
        path: ''
        targetRevision: '{{ .targetRevision }}'
        helm:
          ignoreMissingValueFiles: true
          valueFiles:
          - $helm/values/common/{{ .values.appname }}/values.yaml
          - $helm/values/env/{{ .values.env }}/{{ .values.appname }}/values.yaml
          - $helm/values/env/{{ .values.env }}/{{ .values.appname }}/values-{{.values.region}}.yaml
          - $helm/values/env/{{ .values.env }}/{{ .values.appname }}/values-eks-{{.values.eksversion}}.yaml
          - $helm/values/cluster/{{ .values.cluster }}/values.yaml
      destination:
        server: '{{.server}}'
        namespace: '{{.namespace}}'
